"""
Session-bound agent identity for the governance gateway.

The gateway's agent-integrity gate is only as trustworthy as the identity it checks. In the
first cut, identity was a self-asserted ``agent`` argument — a prompt-injected Reconnaissance
agent could call ``sqlmap(agent="Initial_Access")`` and launder a privilege. This module
binds identity to a per-agent **token carried on the connection** instead: the orchestrator
mints one token per role at setup, hands each agent only its own token (in that agent's MCP
client config), and the gateway maps token -> role. The agent never chooses its identity, and
a call with a missing/unknown token resolves to ``None`` — which the integrity gate treats as
fail-closed.

This module is stdlib-only and import-safe without mcp/langgraph; the header extraction that
actually reads the token off the wire lives in the server and is the only transport-coupled
part.
"""
from __future__ import annotations

import json
import os
import secrets
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# HTTP header the per-agent token rides on (lowercase; matched case-insensitively).
AGENT_TOKEN_HEADER = "x-agent-token"

# Identity resolution modes:
#   "token"     (default, secure) — identity strictly from the connection token; the `agent`
#               argument is ignored. No/unknown token -> None -> fail closed.
#   "trust-arg" (dev only)        — fall back to the self-asserted `agent` argument. This is
#               the old, spoofable behavior; opt-in explicitly and never in production.
MODE_TOKEN = "token"
MODE_TRUST_ARG = "trust-arg"


class AgentIdentityRegistry:
    """Maps connection tokens to agent roles. The gateway holds this; agents never see it."""

    def __init__(self, token_to_role: Optional[Dict[str, str]] = None):
        self._map: Dict[str, str] = dict(token_to_role or {})

    def resolve(self, token: Optional[str]) -> Optional[str]:
        """Token -> role, or None for a missing/unknown token (caller is unidentified)."""
        if not token:
            return None
        return self._map.get(token)

    def roles(self) -> List[str]:
        return sorted(set(self._map.values()))

    # -- provisioning -----------------------------------------------------------------

    @classmethod
    def mint(cls, roles: List[str]) -> Tuple["AgentIdentityRegistry", Dict[str, str]]:
        """Generate a fresh random token per role. Returns (registry, role->token). The
        role->token side is what each agent is provisioned with; the registry (token->role)
        is the gateway's secret."""
        role_to_token = {role: secrets.token_urlsafe(32) for role in roles}
        token_to_role = {tok: role for role, tok in role_to_token.items()}
        return cls(token_to_role), role_to_token

    @classmethod
    def from_env(cls) -> "AgentIdentityRegistry":
        """Load token->role from GATEWAY_TOKENS_FILE (JSON) or GATEWAY_AGENT_TOKENS (JSON
        string). Empty registry when neither is set (every call is then unidentified -> in
        token mode, fail-closed)."""
        path = os.environ.get("GATEWAY_TOKENS_FILE")
        if path and Path(path).exists():
            return cls(json.loads(Path(path).read_text()))
        raw = os.environ.get("GATEWAY_AGENT_TOKENS")
        if raw:
            try:
                return cls(json.loads(raw))
            except json.JSONDecodeError:
                pass
        return cls({})


def resolve_identity(
    registry: AgentIdentityRegistry,
    *,
    token: Optional[str],
    asserted_agent: Optional[str],
    mode: str = MODE_TOKEN,
) -> Tuple[Optional[str], str]:
    """Resolve the caller's role and how it was established.

    Returns (role_or_None, source) where source is "token" | "arg" | "none". In the secure
    default ("token") the asserted argument is ignored entirely; a missing/unknown token
    yields (None, "none") which the integrity gate fails closed on.
    """
    if mode == MODE_TRUST_ARG:
        return (asserted_agent or None), ("arg" if asserted_agent else "none")
    role = registry.resolve(token)
    return (role, "token" if role else "none")


# --- provisioning CLI: mint tokens + write a per-agent gateway config ------------------

def _build_mcp_config(role_to_token: Dict[str, str], url: str) -> Dict[str, object]:
    """A gateway mcp_config where each agent connects with ONLY its own token header.

    Decepticon agent keys are lowercase (planner/reconnaissance/initial_access/summary);
    map them to the role names the gateway/roster use.
    """
    agent_key_to_role = {
        "planner": "Planner", "reconnaissance": "Reconnaissance",
        "initial_access": "Initial_Access", "summary": "Summary",
    }
    cfg: Dict[str, object] = {
        "_comment": ("Generated by governance_gateway.identity --mint. Each agent carries "
                     "ONLY its own per-agent token; the gateway derives identity from this "
                     "header, not from any tool argument. Do NOT commit (contains secrets).")
    }
    for key, role in agent_key_to_role.items():
        token = role_to_token.get(role)
        if not token:
            continue
        cfg[key] = {
            "gateway": {
                "url": url,
                "transport": "streamable_http",
                "headers": {AGENT_TOKEN_HEADER: token},
            }
        }
    return cfg


def main(argv: Optional[List[str]] = None) -> int:
    import argparse

    from .core import GovernanceGateway  # local import to avoid cycle at module load

    parser = argparse.ArgumentParser(
        description="Mint per-agent gateway identity tokens and a matching MCP config."
    )
    parser.add_argument("--mint", action="store_true", help="generate tokens + config files")
    parser.add_argument("--url", default="http://localhost:3000/mcp", help="gateway URL")
    parser.add_argument("--tokens-out", default="gateway_tokens.json",
                        help="gateway secret: token->role (gitignored)")
    parser.add_argument("--config-out", default="mcp_config.gateway.tokens.json",
                        help="per-agent MCP config with token headers (gitignored)")
    args = parser.parse_args(argv)

    if not args.mint:
        parser.print_help()
        return 0

    roles = ["Planner", "Reconnaissance", "Initial_Access", "Summary"]
    registry, role_to_token = AgentIdentityRegistry.mint(roles)
    token_to_role = {tok: role for role, tok in role_to_token.items()}

    Path(args.tokens_out).write_text(json.dumps(token_to_role, indent=2))
    Path(args.config_out).write_text(json.dumps(_build_mcp_config(role_to_token, args.url), indent=2))

    print(f"Wrote {args.tokens_out} (gateway secret: token->role) and {args.config_out} "
          f"(per-agent config).")
    print("Start the gateway with GATEWAY_TOKENS_FILE=" + args.tokens_out +
          " and GATEWAY_IDENTITY_MODE=token,")
    print("and launch the swarm with MCP_CONFIG=" + args.config_out + ".")
    print("Both files contain secrets — they are gitignored; do not commit them.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
